### ISSUE TITLE
Copy of param is value of param

### ISSUE THREAD

**Issue by tscode** [denizyuret/AutoGrad.jl#102]
When I copy a `Param` object, the result is not a `Param`, but its value. Example:
```julia
copy(Param(1)) # returns 1 instead of Param(1)
```
Is this behavior intended? It was certainly surprising for me.

**Comment by denizyuret** [comment]
Outside of a @diff environment, Param(x) is designed to act like x for all
purposes. For example 2*Param(x) gives 2x, not Param(2x). I think the
current behavior of copy is consistent with this.

**Comment by tscode** [comment]
Okay, makes sense. I hit this issue when I wanted to copy self-defined models in the obvious way, and implicitly expected that both the value and the optimizer of the param object would be copied. But this is of course easy to add by hand.

**Comment by NHDaly** [comment]
Fwiw, `deepcopy(x)` seems to still return a `Param`. I'm not sure if that's intended or not, but it's worth noting that it's different than `copy`.

```julia
julia> a = AutoGrad.Param( [1,2,3] )
>> 3-element AutoGrad.Param{Array{Int64,1}}:
 1
 2
 3

julia> deepcopy(a)
>> 3-element AutoGrad.Param{Array{Int64,1}}:
 1
 2
 3
```
