### ISSUE TITLE
mixed Rec and KnetArray problem in vcat

### ISSUE THREAD

**Issue by kirnap** [denizyuret/AutoGrad.jl#21]
when a matrix has mixed Rec and KnetArray, vcat AutoGrad only looks at first 2-3 elements here is the temporary solution:
```
using AutoGrad
let cat_r = recorder(cat); global vcatn
    function vcatn(a...)
        if any(x->isa(x,Rec), a)
            cat_r(1,a...)
        else
            vcat(a...)
        end
    end
end
```
It needs to be put into AutoGrad

**Comment by denizyuret** [comment]
The latest master should have this issue resolved. Regular `cat` should now handle Rec in any position.  Please test...

**Comment by denizyuret** [comment]
@kirnap please test and close.

**Comment by kirnap** [comment]
I tested the different cat versions, namely hcatn, vcatn etc., all the tests passed.
