### ISSUE TITLE
`@dbg` macro never prints error messages for me (julia v0.5.2)

### ISSUE THREAD

**Issue by NHDaly** [denizyuret/AutoGrad.jl#22]
The `@dbg` lines don't seem to print anything for me (Version 0.5.2 (2017-05-06 16:34 UTC))
```julia
julia> AutoGrad.@dbg 1 3+3

julia> AutoGrad.@dbg 1 "Error msg."

julia> AutoGrad.@dbg 0 "Error msg."

julia> AutoGrad.@dbg -1 "Error msg."

julia>
```

---------------

I noticed this because I was perplexed that I didn't see an error message when I first tried the following:

```julia
julia> foo(X) = [x*x for x in X]
foo (generic function with 1 method)

julia> grad(foo)([1,2])

julia>
```

I now understand of course that it's because I'm trying to take the gradient of a non-scalar-value-returning function. But I was sad that I didn't see an error message.

But then I started looking through the code, and saw all these `@dbg` messages, but those don't seem to ever print for me. :(

```julia
julia> using AutoGrad

julia> f(x) = 3
f (generic function with 1 method)

julia> grad(f)(2)

julia>
```
I *think* that should've triggered [this line](https://github.com/denizyuret/AutoGrad.jl/blob/8a338c33f7cc37330d59853e8047f7d3b8a753bf/src/core.jl#L227)?

**Comment by denizyuret** [comment]
In the released version the dbg macro has:

i & 0 != 0;

which makes it do nothing.  When developing, I replace the final 0 with a
nonzero number to print out an appropriate subset of the dbg messages.

best
deniz

**Comment by NHDaly** [comment]
:D haha gotcha, that makes sense! Would you mind if I send a couple PRs that turn some of these debugs into proper `error`s, then? or at least print something to `stderr`?

I was sorta mystified at first when it didn't work (the real code I ran wasn't the toy example I posted above, it was `foo(X) = [if x>0 ; x*x elseif x<0 x^3 ; else 5 end for x in X] ;    grad(foo)([3,-3])`. I wanted to show that `grad` works with control flow, but forgot to turn the input vector into a scalar.

It'd be great to have an error message in times like that! I was instead left wondering if maybe I'm misunderstanding something about the system.

**Comment by denizyuret** [comment]
Absolutely, more helpful error messages and warnings are always welcome!  I am working on Julia6 compatibility and some code restructuring right now, so I suggest waiting for the next version before sending the PRs.
