### ISSUE TITLE
ERROR: Out of gpu memory

### ISSUE THREAD

**Issue by enzotarta** [denizyuret/AutoGrad.jl#29]
Hello,
First of all thanks for the nice package. I'm using it together with Knet and GPUArrays.
I'm running simulations on a deep network (VGG16) on GPU. I noticed that if I use minibatches above a certain dimension (for me, >30) the following error returns:
`ERROR: Out of gpu memory
 in Knet.KnetPtr(::Int64) at /home/enzo/.julia/v0.5/Knet/src/kptr.jl:96
 in relu(::Knet.KnetArray{Float32,4}) at /home/enzo/.julia/v0.5/Knet/src/unary.jl:85
 in (::AutoGrad.##rfun#4#6{Knet.#relu})(::Array{Any,1}, ::Function, ::AutoGrad.Rec{Knet.KnetArray{Float32,4}}, ::Vararg{AutoGrad.Rec{Knet.KnetArray{Float32,4}},N}) at /home/enzo/.julia/v0.5/AutoGrad/src/core.jl:110
 in relu(::AutoGrad.Rec{Knet.KnetArray{Float32,4}}) at ./<missing>:0
 in convnet(::AutoGrad.Rec{Array{Any,1}}, ::Knet.KnetArray{Float32,4}) at /home/enzo/work/hebbianrule/vgg_train.jl:301
 in loss(::AutoGrad.Rec{Array{Any,1}}, ::Knet.KnetArray{Float32,4}, ::Knet.KnetArray{Float32,2}) at /home/enzo/work/hebbianrule/vgg_train.jl:340
 in forward_pass(::Function, ::Tuple{Array{Any,1},Knet.KnetArray{Float32,4},Knet.KnetArray{Float32,2}}, ::Array{Any,1}, ::Int64) at /home/enzo/.julia/v0.5/AutoGrad/src/core.jl:75
 in (::AutoGrad.##gradfun#1#3{VGG.#loss,Int64})(::Array{Any,1}, ::Function, ::Array{Any,1}, ::Vararg{Any,N}) at /home/enzo/.julia/v0.5/AutoGrad/src/core.jl:47
 in (::AutoGrad.#gradfun#2)(::Array{Any,1}, ::Vararg{Any,N}) at /home/enzo/.julia/v0.5/AutoGrad/src/core.jl:47
 in #train!#3(::Int64, ::Int64, ::Float64, ::Float64, ::Float64, ::Float64, ::Function, ::Array{Any,1}, ::Array{Any,1}, ::Array{Float32,3}) at /home/enzo/work/hebbianrule/vgg_train.jl:106
 in (::VGG.#kw##train!)(::Array{Any,1}, ::VGG.#train!, ::Array{Any,1}, ::Array{Any,1}, ::Array{Float32,3}) at ./<missing>:0
 in main(::String) at /home/enzo/work/hebbianrule/vgg_train.jl:80`

which apparently is due the way AutoGrad handles the memory. Is there a way to avoid this memory issue?

**Comment by denizyuret** [comment]
You can do a back-of-the-envelope calculation to see where the memory goes:
in order to take the gradients, the model has to keep all the weights and
all the intermediate results of each layer in memory.  Double all of that
for the gradient arrays.  If this total is close to the GPU memory there is
not much that can be done except working with larger GPUs or smaller
minibatches/models.

**Comment by enzotarta** [comment]
Unfortunately I was aware about this but I hoped there was a different solution to this problem... thanks anyway
