### ISSUE TITLE
Is the example in README  "extending AutoGrad" correct?

### ISSUE THREAD

**Issue by ylxdzsw** [denizyuret/AutoGrad.jl#40]
In current README file https://github.com/denizyuret/AutoGrad.jl#extending-autograd , it says

```
@primitive hypot(x1::Number,x2::Number),dy,y  (dy->dy*x1/y)  (dy->dy*x2/y)
```

However, this defines two functions as the grads. I think the proper way to define it should be

```
@primitive hypot(x1::Number,x2::Number),dy,y  (dy*x1/y)  (dy*x2/y)
```

**Comment by denizyuret** [comment]
Fixed in latest master, thanks.
