### ISSUE TITLE
x.^2 compared with x .* x

### ISSUE THREAD

**Issue by xukai92** [denizyuret/AutoGrad.jl#41]
I tried two implementation of MSE:

```julia
MSE(x, x̂) = mean(sum((x - x̂) .* (x - x̂), 1))
```

and 

```julia
MSE(x, x̂) = mean(sum((x - x̂).^2, 1))
```

, where the latter one can give me `NaN` in the same program but the first one works fine. Any idea why this happens?

**Comment by denizyuret** [comment]
This is a problem with the NVIDIA libraries:
https://github.com/denizyuret/Knet.jl/issues/108

**Comment by xukai92** [comment]
I see. Thx!
