### ISSUE TITLE
Autograd usage problem

### ISSUE THREAD

**Issue by fatihtalu** [denizyuret/AutoGrad.jl#66]
I want to generate the gradient value at [1,2]. I wrote the following code to do this, but it gives an error. Thanks in advance for your help.
```
using Knet
J(w) = w[1]^2 .+ w[2]^2;
dJ = grad(J);
w = [1,2];
println(J(w))
println(dJ(w))
```
**Output:** 
5
MethodError: ^(::AutoGrad.Rec{Int64}, ::Int64) is ambiguous. Candidates:
  ^(x, p::Integer) in Base at intfuncs.jl:199
  ^(x1::AutoGrad.Rec{##1045}, x2::##1046) where {##1045<:Number, ##1046<:Number} in AutoGrad
Possible fix, define
  ^(::AutoGrad.Rec{##1045<:Number}, ::Integer)

**Comment by fatihtalu** [comment]
Trying with broadcast, it gives the following error: 
```println(dJ.(w))```
**Output:**
BoundsError

**Comment by CarloLucibello** [comment]
This has been fixed recently in master (Ref. #48) . Try after
```julia
Pkg.checkout("AutoGrad")
Pkg.checkout("Knet")
```
As an alternative, you could consider evaluating in `[1.0, 2.0]`

**Comment by fatihtalu** [comment]
Thanks CarloLucibello.
After tried [1.0, 2.0], the problem is solved. 
**Output:** 
```
5.0
[2.0, 4.0]
```
