### ISSUE TITLE
grad requires a scalar-valued function

### ISSUE THREAD

**Issue by fatihtalu** [denizyuret/AutoGrad.jl#67]
**Does not it have to be the solution [ [2 0] [0 2] ]  ?** 

![q](https://user-images.githubusercontent.com/22032994/37675146-9085c222-2c85-11e8-9f3b-71c0d09696eb.PNG)

**Comment by CarloLucibello** [comment]
as the error says, autograd requires scalar valued functions, and `df` is not. To obtain the hessian for your example you can use
```julia
julia> g=grad(f)
(::gradfun) (generic function with 1 method)

julia> ddf(w)= [grad(x->g(x)[1])(w) grad(x->g(x)[2])(w)]
ddf (generic function with 1 method)

julia> ddf(w)
2×2 Array{Int64,2}:
 2  0
 0  2
``` 
Also see #54

**Comment by fatihtalu** [comment]
Perfect! exactly as I want.
Thanks CarloLucibello.
