### ISSUE TITLE
Gradient type mismatch

### ISSUE THREAD

**Issue by ekinakyurek** [denizyuret/AutoGrad.jl#69]
`grad` function returns `Array{Float64}` gradient for a `Array{Float32}` input parameter when the differentiated function's output is `Float64`. Is this expected behaviour of `grad`? I think that it has to be same type with input parameters, since we use those gradients for SGD updates.

The issue occurs when I upgraded AutoGrad to the latest commit:  6acb8d58cda13faf178802683c96e49470d74fea

Problem:
```
julia> f(x) = sum(x.*0.2)
f (generic function with 1 method)

julia> gf = grad(f)
(::gradfun) (generic function with 1 method)

julia> gf(ones(Float32,5,5))
5×5 Array{Float64,2}:
 0.2  0.2  0.2  0.2  0.2
 0.2  0.2  0.2  0.2  0.2
 0.2  0.2  0.2  0.2  0.2
 0.2  0.2  0.2  0.2  0.2
 0.2  0.2  0.2  0.2  0.2
```

If we remove 0.2 in `sum`, there is no problem:
```
julia> f(x) = sum(x)
f (generic function with 1 method)

julia> gf = grad(f)
(::gradfun) (generic function with 1 method)

julia> gf(ones(Float32,5,5))
5×5 Array{Float32,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
```

**Comment by ozanarkancan** [comment]
I guess it is expected behavior. You should use Float32(0.2).
