### ISSUE TITLE
non-scalar loss function

### ISSUE THREAD

**Issue by jbrea** [denizyuret/AutoGrad.jl#70]
I try to circumvent the limitation of a scalar loss function by (deep) copying the recorded tape at the right moment, e.g.

```julia
import AutoGrad: Tape, Rec, backward_pass
tape = Tape()
w = rand(2, 4)
w = Rec(w, tape)
x = rand(4)
y = w * x # or a deep neural net
y2 = deepcopy(y)
endbox1 = (y[1] - 1)^2
endbox2 = (y2[2] - 3)^4
g1 = backward_pass(w, endbox1, endbox1.tapes[1])
g2 = backward_pass(w, endbox2, endbox2.tapes[1])
g = 0.1 * g1 + g2
```
Is there a more elegant way to achieve this?

**Comment by CarloLucibello** [comment]
How is that different from defining the scalar loss
```julia
loss(y) = 0.1 * (y[1] - 1)^2  +  (y[2] - 3)^4 
```
? Do you have a more complicated example where a non-scalar loss is really needed?

**Comment by jbrea** [comment]
You are right :) I don't recall, how I arrived at this question :)
